/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
const Recipe = /* GraphQL */ `
  type Recipe {
    _id: ID!
    title: String!
    vegetarian: Boolean!
    ingredients: [Ingredient!]!
    preparation: [String!]!
  }
`;

export default Recipe;
