/**
 * The entry point for our GraphQL server
 *
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
import express from 'express';
import bodyParser from 'body-parser';
import { graphqlExpress, graphiqlExpress } from 'graphql-server-express';
import schema from './schema';
import cors from 'cors';

const PORT = 3001;
const GRAPHQL_PATH = '/';
const GRAPHIQL_PATH = '/graphiql';

const app = express();

app.use(cors());

// Set up GraphiQL
app.use(GRAPHIQL_PATH, graphiqlExpress({
  endpointURL: GRAPHQL_PATH,
}));

// Set up the GraphQL endpoint
app.use(GRAPHQL_PATH, bodyParser.json(), graphqlExpress({ schema }));

app.listen(PORT);

console.log(`GraphQL server started, listening at http://localhost:${PORT}${GRAPHQL_PATH}`);
console.log(`GraphiQL enabled, running at http://localhost:${PORT}${GRAPHIQL_PATH}`)
