/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
import { graphql } from 'graphql';
import { mockDb, setup, teardown } from './mock-db';
jest.mock('../models/db', () => mockDb);

import schema from '../schema';

beforeAll(() => teardown());
afterAll(() => teardown());

describe('GraphQL server', () => {
  beforeEach(() => setup());
  afterEach(() => teardown());

  describe('Queries', () => {
    it('should return a list of recipes', () => {
      expect.assertions(1);
      const query = /* GraphQL */ `
        {
          recipes {
            title
            vegetarian
            preparation
          }
        }
      `;
      return graphql(schema, query).then(result => {
        expect(result).toMatchSnapshot();
      });
    });

    it('should return a list of recipes with its ingredients', () => {
      expect.assertions(1);
      const query = /* GraphQL */ `
        {
          recipes {
            title
            vegetarian
            preparation
            ingredients {
              _id
              name
            }
          }
        }
      `;
      return graphql(schema, query).then(result => {
        expect(result).toMatchSnapshot();
      });
    });

    it('should filter results by vegetarianism', () => {
      expect.assertions(1);
      const query = /* GraphQL */ `
        {
          recipes(vegetarian: true) {
            title
          }
        }
      `;
      return graphql(schema, query).then(result => {
        expect(result).toMatchSnapshot();
      });
    });

    it('should filter results by not vegetarianism', () => {
      expect.assertions(1);
      const query = /* GraphQL */ `
        {
          recipes(vegetarian: false) {
            title
          }
        }
      `;
      return graphql(schema, query).then(result => {
        expect(result).toMatchSnapshot();
      });
    });

    it('should filter results by ingredient ID', () => {
      expect.assertions(1);
      const query = /* GraphQL */ `
        {
          recipes(ingredient: "123asdf") {
            title
          }
        }
      `;
      return graphql(schema, query).then(result => {
        expect(result).toMatchSnapshot();
      });
    });
  });
});
