/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
import { ingredientDb } from './db';

/**
 * Get an ingredient by its _id
 *
 * @param  {String} _id
 *
 * @returns {Promise<Ingredient>}
 */
export const getIngredient = _id =>
  ingredientDb.find({ _id }).then(result => result && result[0]);

/**
 * Add an ingredient with a certain name
 *
 * @param {String} name
 * @returns {Promise<NewIngredient>}
 */
export const addIngredient = name => ingredientDb.insert({ name });

/**
 * Get a list of all ingredients
 *
 * @returns {Promise<[Ingredient]>}
 */
export const getIngredients = () => ingredientDb.find({});
