/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
import { recipeDb } from './db';

/**
 * Get a list of all the recipes that match the optionally provided filters
 *
 * @param  {Bool} vegetarian Should only return vegetarian or non-vegetarian recipes
 * @param  {String} ingredient Should only return recipes that contain that ingredient
 *
 * @returns {Promise<[Recipe]>}
 */
export const getRecipes = ({ vegetarian, ingredient }) => {
  // Construct the filters
  let filters = {};
  if (typeof vegetarian !== 'undefined') filters.vegetarian = !!vegetarian;
  if (ingredient) {
    filters.ingredients = {
      $elemMatch: ingredient
    };
  }
  return recipeDb.find(filters);
};

/**
 * Add a recipe to the database
 *
 * @param {Object} input
 * @param {String} input.title
 * @param {Bool}   input.vegetarian
 * @param {Array}  input.preparation An array of steps of preparation (i.e. an array of strings)
 * @param {Array}  input.ingredients An array of ingredient IDs with their amount, e.g. { amount: '30g', ingredient: 'asdf123' }
 *
 * @returns {Promise<NewRecipe>}
 */
export const addRecipe = input => {
  return recipeDb.insert(input);
};
