/**
 * npm run seed
 * to seed the database with some initial data
 *
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
import { recipeDb, ingredientDb } from './db';

Promise.all([
  ingredientDb.insert([
    {
      _id: 'asdf123',
      name: 'Salad'
    },
    {
      _id: 'asdf234',
      name: 'Salad dressing'
    },
    {
      _id: '123asdf',
      name: 'Beef'
    },
    {
      _id: '234asdf',
      name: 'Chicken'
    }
  ]),
  recipeDb.insert([
    {
      _id: '1-recipe',
      title: 'Wiener Schnitzel',
      vegetarian: false,
      ingredients: ['123asdf', 'asdf123', 'asdf234'],
      preparation: ['Get ingredients', 'Put beef into pan', 'Enjoy']
    },
    {
      _id: '2-recipe',
      title: 'Caesar Salad',
      vegetarian: false,
      ingredients: ['234asdf', 'asdf123', 'asdf234'],
      preparation: ['Get ingredients', 'Put them all in a bowl', 'Enjoy']
    },
    {
      _id: '3-recipe',
      title: 'Salad',
      vegetarian: true,
      ingredients: ['asdf123', 'asdf234'],
      preparation: ['Get ingredients', 'Put them all in a bowl', 'Enjoy']
    }
  ])
]).then(() => {
  console.log('✅ Database seeding successful.');
}).catch((err) => {
  console.log('⚠️ Database seeding error ⚠️');
  console.log(err);
})
